### ISSUE TITLE
[Question] error while compiling png files to avif

### ISSUE THREAD

**Issue by mimmi20** [vHeemstra/imagemin-avifenc#1]
I get this error when I want to compile png files to avif.

```shell
  public/dist/assets/logo-1wwMKIqh.png
   └─ public/dist/assets/logo-1wwMKIqh.png.avif                    ERROR  Error processing file:
/home/developer/projects/VT-68944/node_modules/@vheemstra/avifenc-bin/vendor/avifenc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/developer/projects/VT-68944/node_modules/@vheemstra/avifenc-bin/vendor/avifenc)
/home/developer/projects/VT-68944/node_modules/@vheemstra/avifenc-bin/vendor/avifenc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/developer/projects/VT-68944/node_modules/@vheemstra/avifenc-bin/vendor/avifenc)
```

Do I need to install something to use this module?

**Comment by vHeemstra** [comment]
Good question.

It seems that the Linux binary needs a version of that module that is either missing or different on your system.

Since I'm not that familiar with Linux, I'm not really sure if I can help you here. But searching the error gave me this thread on SO: https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found

Seems like running these two commands might fix this issue:
```sh
sudo apt update
sudo apt install libc6
```

If that doesn't work, you might look into the info on that page for more help.

**Comment by mimmi20** [comment]
It looks like, my Linux is just too old.
